###########
# site.url, site.title

url:   "http://openbeer.github.io"
title: "beer.db - Open Beer, Brewery n Brewpubs Data"


########
# more settings

markdown: kramdown


exclude: ["README.md"]

safe: true
lsi: false

